// Phase 7 & Phase 8 Comprehensive Seed Data
import {
  Department,
  EmployeeProfile,
  EmployeeDocument,
  EmployeeShift,
  AttendanceRecord,
  LeaveType,
  LeaveBalance,
  LeaveRequest,
  EmployeeCompensation,
  RoleDefinition,
  UserSession,
  LoginHistoryRecord,
  SecurityEvent,
  BackupJob,
  ExportJob,
  IntegrationConfig,
  ApiKeyRecord,
  WebhookRecord,
  FeatureFlag,
  SaaSPlan,
  OrganizationSubscription,
  UsageMetricRecord,
  SystemAnnouncement,
  TelemedicineRoom,
  TelemedicineMessage,
  TelemedicineEvent,
  InsuranceProvider,
  InsurancePolicy,
  PreAuthorization,
  InsuranceClaim,
  ClaimSettlement,
  DoctorShift,
  OnCallRoster,
  DrugSafetyWarning,
  DrugSafetyEvent,
  BackgroundJobRecord,
  SystemHealthCheck,
} from '../types';

export const INITIAL_DEPARTMENTS: Department[] = [
  {
    id: 'dept-01',
    organizationId: 'org-01',
    branchId: 'branch-01',
    name: 'General Medicine & Family Practice',
    code: 'MED-GEN',
    description: 'Primary clinical consultations, chronic disease management, and wellness checks.',
    headId: 'doc-01',
    headName: 'Dr. Sarah Jenkins, MD',
    status: 'Active',
    createdAt: '2026-01-01T00:00:00Z',
  },
  {
    id: 'dept-02',
    organizationId: 'org-01',
    branchId: 'branch-01',
    name: 'Cardiology & Vascular Medicine',
    code: 'CARD-01',
    description: 'Comprehensive cardiovascular diagnostics, echocardiography, and hypertension management.',
    headId: 'doc-02',
    headName: 'Dr. Michael Chen, MD',
    status: 'Active',
    createdAt: '2026-01-01T00:00:00Z',
  },
  {
    id: 'dept-03',
    organizationId: 'org-01',
    branchId: 'branch-01',
    name: 'Orthopedics & Sports Medicine',
    code: 'ORTHO-01',
    description: 'Joint preservation, arthroscopic procedures, fracture management, and musculoskeletal rehabilitation.',
    headId: 'doc-04',
    headName: 'Dr. David Kim, MD',
    status: 'Active',
    createdAt: '2026-01-01T00:00:00Z',
  },
  {
    id: 'dept-04',
    organizationId: 'org-01',
    branchId: 'branch-01',
    name: 'Pediatrics & Adolescent Care',
    code: 'PED-01',
    description: 'Infant wellness, neurodevelopmental assessment, immunizations, and acute pediatric care.',
    headId: 'doc-05',
    headName: 'Dr. Priya Patel, MD',
    status: 'Active',
    createdAt: '2026-01-01T00:00:00Z',
  },
  {
    id: 'dept-05',
    organizationId: 'org-01',
    branchId: 'branch-01',
    name: 'Nursing & Clinical Operations',
    code: 'OPS-NURS',
    description: 'Triage, vital monitoring, intravenous access, patient preparation, and outpatient care.',
    headId: 'emp-03',
    headName: 'Jennifer Collins, RN',
    status: 'Active',
    createdAt: '2026-01-01T00:00:00Z',
  },
  {
    id: 'dept-06',
    organizationId: 'org-01',
    branchId: 'branch-01',
    name: 'Finance, Billing & Patient Accounts',
    code: 'FIN-01',
    description: 'Patient insurance claims, point-of-sale collections, corporate tie-ups, and ledger auditing.',
    headId: 'emp-04',
    headName: 'Daniel Weber, CPA',
    status: 'Active',
    createdAt: '2026-01-01T00:00:00Z',
  },
];

export const INITIAL_EMPLOYEES: EmployeeProfile[] = [
  {
    id: 'emp-01',
    employeeId: 'EMP-2026-001',
    organizationId: 'org-01',
    branchId: 'branch-01',
    branchName: 'Downtown Central Clinic',
    name: 'Dr. Sarah Jenkins, MD',
    photo: 'https://images.unsplash.com/photo-1594824813581-2292f7243c52?auto=format&fit=crop&q=80&w=300',
    gender: 'Female',
    dateOfBirth: '1984-06-14',
    phone: '+1 (555) 234-5678',
    email: 'sarah.jenkins@apexhealthclinics.com',
    address: '742 Evergreen Terrace, New York, NY 10001',
    emergencyContactName: 'Mark Jenkins (Spouse)',
    emergencyContactPhone: '+1 (555) 234-9988',
    emergencyRelationship: 'Spouse',
    departmentId: 'dept-01',
    departmentName: 'General Medicine & Family Practice',
    role: 'DOCTOR',
    joiningDate: '2021-04-15',
    employmentType: 'Full Time',
    status: 'Active',
    notes: 'Lead Physician and Clinical Director.',
    createdAt: '2021-04-15T00:00:00Z',
  },
  {
    id: 'emp-02',
    employeeId: 'EMP-2026-002',
    organizationId: 'org-01',
    branchId: 'branch-01',
    branchName: 'Downtown Central Clinic',
    name: 'Dr. Michael Chen, MD',
    photo: 'https://images.unsplash.com/photo-1622253692010-333f2da6031d?auto=format&fit=crop&q=80&w=300',
    gender: 'Male',
    dateOfBirth: '1982-11-20',
    phone: '+1 (555) 345-6789',
    email: 'michael.chen@apexhealthclinics.com',
    address: '120 Riverside Drive, Apt 4B, New York, NY 10024',
    emergencyContactName: 'Grace Chen (Sister)',
    emergencyContactPhone: '+1 (555) 345-8811',
    emergencyRelationship: 'Sister',
    departmentId: 'dept-02',
    departmentName: 'Cardiology & Vascular Medicine',
    role: 'DOCTOR',
    joiningDate: '2022-01-10',
    employmentType: 'Full Time',
    status: 'Active',
    notes: 'Senior Interventional Cardiologist.',
    createdAt: '2022-01-10T00:00:00Z',
  },
  {
    id: 'emp-03',
    employeeId: 'EMP-2026-003',
    organizationId: 'org-01',
    branchId: 'branch-01',
    branchName: 'Downtown Central Clinic',
    name: 'Jennifer Collins, RN',
    photo: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&q=80&w=300',
    gender: 'Female',
    dateOfBirth: '1990-03-22',
    phone: '+1 (555) 456-7890',
    email: 'jennifer.collins@apexhealthclinics.com',
    address: '88 Lexington Ave, New York, NY 10016',
    emergencyContactName: 'Thomas Collins (Father)',
    emergencyContactPhone: '+1 (555) 456-9900',
    emergencyRelationship: 'Father',
    departmentId: 'dept-05',
    departmentName: 'Nursing & Clinical Operations',
    role: 'NURSE',
    joiningDate: '2022-08-01',
    employmentType: 'Full Time',
    status: 'Active',
    notes: 'Head Clinical Nurse, CPR Instructor.',
    createdAt: '2022-08-01T00:00:00Z',
  },
  {
    id: 'emp-04',
    employeeId: 'EMP-2026-004',
    organizationId: 'org-01',
    branchId: 'branch-01',
    branchName: 'Downtown Central Clinic',
    name: 'Daniel Weber, CPA',
    photo: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&q=80&w=300',
    gender: 'Male',
    dateOfBirth: '1988-09-05',
    phone: '+1 (555) 567-8901',
    email: 'daniel.weber@apexhealthclinics.com',
    address: '300 West 23rd St, New York, NY 10011',
    emergencyContactName: 'Laura Weber (Spouse)',
    emergencyContactPhone: '+1 (555) 567-1122',
    emergencyRelationship: 'Spouse',
    departmentId: 'dept-06',
    departmentName: 'Finance, Billing & Patient Accounts',
    role: 'ACCOUNTANT',
    joiningDate: '2023-02-15',
    employmentType: 'Full Time',
    status: 'Active',
    notes: 'Chief Financial Accountant.',
    createdAt: '2023-02-15T00:00:00Z',
  },
  {
    id: 'emp-05',
    employeeId: 'EMP-2026-005',
    organizationId: 'org-01',
    branchId: 'branch-01',
    branchName: 'Downtown Central Clinic',
    name: 'Rachel Gomez',
    photo: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?auto=format&fit=crop&q=80&w=300',
    gender: 'Female',
    dateOfBirth: '1995-12-18',
    phone: '+1 (555) 678-9012',
    email: 'rachel.gomez@apexhealthclinics.com',
    address: '45 Tudor City Place, New York, NY 10017',
    emergencyContactName: 'Carlos Gomez (Brother)',
    emergencyContactPhone: '+1 (555) 678-4455',
    emergencyRelationship: 'Brother',
    departmentId: 'dept-05',
    departmentName: 'Nursing & Clinical Operations',
    role: 'RECEPTIONIST',
    joiningDate: '2023-05-10',
    employmentType: 'Full Time',
    status: 'Active',
    notes: 'Senior Front Desk Coordinator & Patient Liaison.',
    createdAt: '2023-05-10T00:00:00Z',
  },
  {
    id: 'emp-06',
    employeeId: 'EMP-2026-006',
    organizationId: 'org-01',
    branchId: 'branch-02',
    branchName: 'Metro North Specialty Pavilion',
    name: 'Dr. David Kim, MD',
    photo: 'https://images.unsplash.com/photo-1612349317150-e413f6a5b16d?auto=format&fit=crop&q=80&w=300',
    gender: 'Male',
    dateOfBirth: '1980-07-29',
    phone: '+1 (555) 789-0123',
    email: 'david.kim@apexhealthclinics.com',
    address: '520 2nd Avenue, New York, NY 10016',
    emergencyContactName: 'Susan Kim (Spouse)',
    emergencyContactPhone: '+1 (555) 789-3344',
    emergencyRelationship: 'Spouse',
    departmentId: 'dept-03',
    departmentName: 'Orthopedics & Sports Medicine',
    role: 'DOCTOR',
    joiningDate: '2022-06-01',
    employmentType: 'Full Time',
    status: 'Active',
    notes: 'Consultant Orthopedic Surgeon.',
    createdAt: '2022-06-01T00:00:00Z',
  },
];

export const INITIAL_EMPLOYEE_DOCUMENTS: EmployeeDocument[] = [
  {
    id: 'doc-emp-01',
    employeeId: 'emp-01',
    title: 'State Medical Board License - NY',
    category: 'Qualification',
    fileName: 'Dr_Jenkins_Medical_License_2026.pdf',
    fileSize: '1.4 MB',
    fileUrl: '#',
    uploadedBy: 'Administrator',
    uploadedAt: '2026-01-10T10:00:00Z',
  },
  {
    id: 'doc-emp-02',
    employeeId: 'emp-01',
    title: 'Board Certification in Family Medicine (ABFM)',
    category: 'Certificate',
    fileName: 'ABFM_Certification_Jenkins.pdf',
    fileSize: '890 KB',
    fileUrl: '#',
    uploadedBy: 'Administrator',
    uploadedAt: '2026-01-10T10:05:00Z',
  },
  {
    id: 'doc-emp-03',
    employeeId: 'emp-03',
    title: 'Registered Nurse Practicing License (RN)',
    category: 'Certificate',
    fileName: 'RN_License_Collins.pdf',
    fileSize: '650 KB',
    fileUrl: '#',
    uploadedBy: 'Administrator',
    uploadedAt: '2026-02-01T09:30:00Z',
  },
];

export const INITIAL_EMPLOYEE_SHIFTS: EmployeeShift[] = [
  {
    id: 'shift-01',
    name: 'Morning Clinical Shift',
    startTime: '08:00',
    endTime: '16:00',
    breakMinutes: 45,
    gracePeriodMinutes: 15,
    branchId: 'branch-01',
    status: 'Active',
  },
  {
    id: 'shift-02',
    name: 'General Operational Shift',
    startTime: '09:00',
    endTime: '17:00',
    breakMinutes: 60,
    gracePeriodMinutes: 15,
    branchId: 'branch-01',
    status: 'Active',
  },
  {
    id: 'shift-03',
    name: 'Evening Specialty Shift',
    startTime: '13:00',
    endTime: '21:00',
    breakMinutes: 45,
    gracePeriodMinutes: 15,
    branchId: 'branch-01',
    status: 'Active',
  },
  {
    id: 'shift-04',
    name: 'Urgent Care Weekend Shift',
    startTime: '09:00',
    endTime: '15:00',
    breakMinutes: 30,
    gracePeriodMinutes: 10,
    branchId: 'branch-01',
    status: 'Active',
  },
];

export const INITIAL_ATTENDANCE: AttendanceRecord[] = [
  {
    id: 'att-01',
    employeeId: 'emp-01',
    employeeName: 'Dr. Sarah Jenkins, MD',
    departmentName: 'General Medicine',
    branchId: 'branch-01',
    date: '2026-03-03',
    clockIn: '07:54',
    clockOut: '16:15',
    workedDurationMinutes: 501,
    status: 'Present',
    notes: 'Completed full clinical schedule.',
  },
  {
    id: 'att-02',
    employeeId: 'emp-02',
    employeeName: 'Dr. Michael Chen, MD',
    departmentName: 'Cardiology',
    branchId: 'branch-01',
    date: '2026-03-03',
    clockIn: '08:05',
    clockOut: '16:30',
    workedDurationMinutes: 505,
    status: 'Present',
    notes: 'Echo diagnostic session.',
  },
  {
    id: 'att-03',
    employeeId: 'emp-03',
    employeeName: 'Jennifer Collins, RN',
    departmentName: 'Nursing',
    branchId: 'branch-01',
    date: '2026-03-03',
    clockIn: '07:50',
    clockOut: '16:02',
    workedDurationMinutes: 492,
    status: 'Present',
    notes: 'Triage desk lead.',
  },
  {
    id: 'att-04',
    employeeId: 'emp-04',
    employeeName: 'Daniel Weber, CPA',
    departmentName: 'Finance',
    branchId: 'branch-01',
    date: '2026-03-03',
    clockIn: '09:12',
    clockOut: '17:25',
    workedDurationMinutes: 493,
    status: 'Late',
    notes: 'Delayed due to subway signal work; notified supervisor.',
  },
  {
    id: 'att-05',
    employeeId: 'emp-05',
    employeeName: 'Rachel Gomez',
    departmentName: 'Nursing & Operations',
    branchId: 'branch-01',
    date: '2026-03-03',
    clockIn: '08:45',
    clockOut: '17:05',
    workedDurationMinutes: 500,
    status: 'Present',
    notes: 'Reception desk shift.',
  },
];

export const INITIAL_LEAVE_TYPES: LeaveType[] = [
  { id: 'lt-01', name: 'Annual / Paid Leave', code: 'AL', daysAllowed: 20, carryForward: true, status: 'Active' },
  { id: 'lt-02', name: 'Sick / Medical Leave', code: 'SL', daysAllowed: 12, carryForward: false, status: 'Active' },
  { id: 'lt-03', name: 'Casual / Personal Leave', code: 'CL', daysAllowed: 8, carryForward: false, status: 'Active' },
  { id: 'lt-04', name: 'Continuing Medical Education (CME)', code: 'CME', daysAllowed: 5, carryForward: false, status: 'Active' },
];

export const INITIAL_LEAVE_BALANCES: LeaveBalance[] = [
  { id: 'lb-01', employeeId: 'emp-01', leaveTypeId: 'lt-01', leaveTypeName: 'Annual / Paid Leave', totalDays: 20, usedDays: 4, remainingDays: 16, year: 2026 },
  { id: 'lb-02', employeeId: 'emp-01', leaveTypeId: 'lt-02', leaveTypeName: 'Sick / Medical Leave', totalDays: 12, usedDays: 1, remainingDays: 11, year: 2026 },
  { id: 'lb-03', employeeId: 'emp-01', leaveTypeId: 'lt-04', leaveTypeName: 'CME Leave', totalDays: 5, usedDays: 2, remainingDays: 3, year: 2026 },
  { id: 'lb-04', employeeId: 'emp-05', leaveTypeId: 'lt-01', leaveTypeName: 'Annual / Paid Leave', totalDays: 15, usedDays: 2, remainingDays: 13, year: 2026 },
];

export const INITIAL_LEAVE_REQUESTS: LeaveRequest[] = [
  {
    id: 'lr-01',
    employeeId: 'emp-01',
    employeeName: 'Dr. Sarah Jenkins, MD',
    department: 'General Medicine',
    branchId: 'branch-01',
    leaveTypeId: 'lt-04',
    leaveTypeName: 'CME Leave',
    startDate: '2026-03-25',
    endDate: '2026-03-27',
    totalDays: 3,
    reason: 'Attending American College of Physicians National Scientific Conference.',
    status: 'Approved',
    reviewedBy: 'Administrator',
    reviewedAt: '2026-02-28T14:00:00Z',
    reviewNotes: 'Locum physician Dr. Patel assigned for call coverage.',
    createdAt: '2026-02-25T10:00:00Z',
  },
  {
    id: 'lr-02',
    employeeId: 'emp-05',
    employeeName: 'Rachel Gomez',
    department: 'Nursing & Operations',
    branchId: 'branch-01',
    leaveTypeId: 'lt-03',
    leaveTypeName: 'Casual / Personal Leave',
    startDate: '2026-03-16',
    endDate: '2026-03-17',
    totalDays: 2,
    reason: 'Family wedding out of state.',
    status: 'Pending',
    createdAt: '2026-03-01T09:15:00Z',
  },
];

export const INITIAL_COMPENSATIONS: EmployeeCompensation[] = [
  {
    id: 'comp-01',
    employeeId: 'emp-01',
    employeeName: 'Dr. Sarah Jenkins, MD',
    currency: 'USD',
    baseSalary: 18500,
    paymentFrequency: 'Monthly',
    allowances: [
      { name: 'Clinical Supervision Allowance', amount: 1500, isTaxable: true },
      { name: 'CME & Medical Book Stipend', amount: 400, isTaxable: false },
    ],
    deductions: [
      { name: 'State & Federal Withholding', amount: 4800 },
      { name: 'Medical & Dental Plan', amount: 350 },
    ],
    effectiveDate: '2026-01-01',
    status: 'Active',
    bankAccountMasked: 'Chase Bank •••• 8841',
  },
  {
    id: 'comp-02',
    employeeId: 'emp-03',
    employeeName: 'Jennifer Collins, RN',
    currency: 'USD',
    baseSalary: 7200,
    paymentFrequency: 'Monthly',
    allowances: [
      { name: 'Shift Lead Differential', amount: 450, isTaxable: true },
    ],
    deductions: [
      { name: 'State & Federal Tax', amount: 1650 },
      { name: 'Healthcare Insurance', amount: 200 },
    ],
    effectiveDate: '2026-01-01',
    status: 'Active',
    bankAccountMasked: 'Citibank •••• 3912',
  },
  {
    id: 'comp-03',
    employeeId: 'emp-05',
    employeeName: 'Rachel Gomez',
    currency: 'USD',
    baseSalary: 4200,
    paymentFrequency: 'Monthly',
    allowances: [
      { name: 'Bilingual Support Bonus', amount: 250, isTaxable: true },
    ],
    deductions: [
      { name: 'Income Tax', amount: 840 },
    ],
    effectiveDate: '2026-01-01',
    status: 'Active',
    bankAccountMasked: 'Bank of America •••• 9210',
  },
];

export const INITIAL_ROLES: RoleDefinition[] = [
  {
    id: 'role-sa',
    name: 'Super Admin',
    description: 'Universal master controls across all clinic branches, database configurations, and SaaS tiers.',
    isSystem: true,
    permissions: ['all'],
    userCount: 2,
  },
  {
    id: 'role-ca',
    name: 'Clinic Admin',
    description: 'Full organizational authority over patients, staff, clinical billing, inventory, and branch settings.',
    isSystem: true,
    permissions: ['patients.*', 'appointments.*', 'doctors.*', 'billing.*', 'crm.*', 'reports.*', 'hr.*', 'telemedicine.*'],
    userCount: 4,
  },
  {
    id: 'role-doc',
    name: 'Doctor / Specialist',
    description: 'Clinical consultation suite, digital prescriptions, lab orders, EMR history, and telemedicine rooms.',
    isSystem: true,
    permissions: ['patients.view', 'appointments.view', 'consultations.*', 'prescriptions.*', 'labs.*', 'telemedicine.*'],
    userCount: 8,
  },
  {
    id: 'role-rec',
    name: 'Receptionist / Front Desk',
    description: 'Patient check-in, token queue management, appointment scheduling, and primary contact intake.',
    isSystem: true,
    permissions: ['patients.create', 'patients.edit', 'appointments.*', 'billing.create', 'crm.tasks'],
    userCount: 5,
  },
  {
    id: 'role-acc',
    name: 'Accountant / Billing Clerk',
    description: 'Cashier invoicing, payment receipts, insurance settlement entries, and financial ledgers.',
    isSystem: true,
    permissions: ['billing.*', 'insurance.*', 'reports.financial'],
    userCount: 3,
  },
  {
    id: 'role-stf',
    name: 'Clinical Staff / Nurse',
    description: 'Vital sign intake, patient preparation, triage staging, and inventory dispensing.',
    isSystem: true,
    permissions: ['patients.view', 'vitals.edit', 'inventory.view', 'appointments.view'],
    userCount: 6,
  },
];

export const INITIAL_USER_SESSIONS: UserSession[] = [
  {
    id: 'sess-01',
    userId: 'usr-admin-01',
    userName: 'Clinic Administrator',
    userRole: 'CLINIC_ADMIN',
    ipAddress: '198.51.100.42',
    device: 'Desktop Mac (Apple Silicon)',
    browser: 'Chrome 122.0',
    location: 'New York, US',
    lastActive: 'Just now',
    createdAt: '2026-03-03T08:00:00Z',
    isCurrent: true,
  },
  {
    id: 'sess-02',
    userId: 'usr-doc-01',
    userName: 'Dr. Sarah Jenkins, MD',
    userRole: 'DOCTOR',
    ipAddress: '198.51.100.89',
    device: 'iPad Pro 12.9"',
    browser: 'Safari Mobile',
    location: 'New York, US',
    lastActive: '12 minutes ago',
    createdAt: '2026-03-03T08:30:00Z',
    isCurrent: false,
  },
  {
    id: 'sess-03',
    userId: 'usr-rec-01',
    userName: 'Rachel Gomez',
    userRole: 'RECEPTIONIST',
    ipAddress: '192.168.1.45 (Local LAN)',
    device: 'Dell OptiPlex Terminal',
    browser: 'Edge 121.0',
    location: 'Downtown Central Clinic',
    lastActive: '2 minutes ago',
    createdAt: '2026-03-03T07:45:00Z',
    isCurrent: false,
  },
];

export const INITIAL_LOGIN_HISTORY: LoginHistoryRecord[] = [
  { id: 'lh-01', email: 'admin@apexhealthclinics.com', role: 'CLINIC_ADMIN', timestamp: '2026-03-03T08:00:00Z', success: true, ipAddress: '198.51.100.42', userAgent: 'Chrome/122.0 (Macintosh)', loginMethod: '2FA' },
  { id: 'lh-02', email: 'sarah.jenkins@apexhealthclinics.com', role: 'DOCTOR', timestamp: '2026-03-03T07:54:00Z', success: true, ipAddress: '198.51.100.89', userAgent: 'Safari/17.2 (iPadOS)', loginMethod: 'Password' },
  { id: 'lh-03', email: 'rachel.gomez@apexhealthclinics.com', role: 'RECEPTIONIST', timestamp: '2026-03-03T07:45:00Z', success: true, ipAddress: '192.168.1.45', userAgent: 'Edge/121.0 (Windows NT)', loginMethod: 'Password' },
  { id: 'lh-04', email: 'daniel.weber@apexhealthclinics.com', role: 'ACCOUNTANT', timestamp: '2026-03-03T07:40:12Z', success: false, ipAddress: '192.168.1.99', userAgent: 'Firefox/123.0', loginMethod: 'Password', failureReason: 'Incorrect credential hash entered' },
  { id: 'lh-05', email: 'daniel.weber@apexhealthclinics.com', role: 'ACCOUNTANT', timestamp: '2026-03-03T07:41:05Z', success: true, ipAddress: '192.168.1.99', userAgent: 'Firefox/123.0', loginMethod: 'Password' },
];

export const INITIAL_SECURITY_EVENTS: SecurityEvent[] = [
  { id: 'sec-01', type: '2FA_TOGGLED', userId: 'usr-admin-01', userName: 'Clinic Administrator', details: 'Hardware FIDO2 Security Key enrolled as primary authenticator.', ipAddress: '198.51.100.42', timestamp: '2026-02-20T11:20:00Z' },
  { id: 'sec-02', type: 'PASSWORD_CHANGE', userId: 'usr-doc-01', userName: 'Dr. Sarah Jenkins', details: 'Periodic 90-day HIPAA password renewal completed successfully.', ipAddress: '198.51.100.89', timestamp: '2026-02-15T09:00:00Z' },
  { id: 'sec-03', type: 'SESSION_REVOKED', userId: 'usr-admin-01', details: 'Terminated inactive workstation session in exam room 3.', ipAddress: '192.168.1.20', timestamp: '2026-02-10T18:00:00Z' },
];

export const INITIAL_BACKUP_JOBS: BackupJob[] = [
  {
    id: 'bck-01',
    provider: 'GCS Cloud',
    schedule: 'Daily',
    retentionDays: 30,
    encryptionEnabled: true,
    status: 'Completed',
    sizeBytes: 84250000,
    startedAt: '2026-03-03T02:00:00Z',
    completedAt: '2026-03-03T02:04:15Z',
  },
  {
    id: 'bck-02',
    provider: 'GCS Cloud',
    schedule: 'Daily',
    retentionDays: 30,
    encryptionEnabled: true,
    status: 'Completed',
    sizeBytes: 83120000,
    startedAt: '2026-03-02T02:00:00Z',
    completedAt: '2026-03-02T02:03:50Z',
  },
  {
    id: 'bck-03',
    provider: 'Local Storage',
    schedule: 'Weekly',
    retentionDays: 90,
    encryptionEnabled: true,
    status: 'Completed',
    sizeBytes: 84100000,
    startedAt: '2026-03-01T03:00:00Z',
    completedAt: '2026-03-01T03:05:10Z',
  },
];

export const INITIAL_EXPORT_JOBS: ExportJob[] = [
  {
    id: 'exp-01',
    type: 'Patients',
    status: 'Completed',
    requestedBy: 'Clinic Administrator',
    format: 'CSV',
    rowCount: 24,
    downloadUrl: '#',
    expiresAt: '2026-03-10T23:59:59Z',
    createdAt: '2026-03-02T16:00:00Z',
  },
  {
    id: 'exp-02',
    type: 'Billing',
    status: 'Completed',
    requestedBy: 'Daniel Weber, CPA',
    format: 'CSV',
    rowCount: 38,
    downloadUrl: '#',
    expiresAt: '2026-03-10T23:59:59Z',
    createdAt: '2026-03-01T11:30:00Z',
  },
];

export const INITIAL_INTEGRATIONS: IntegrationConfig[] = [
  {
    id: 'int-01',
    key: 'whatsapp',
    name: 'WhatsApp Business API Gateway',
    provider: 'Meta Cloud API / Twilio WhatsApp',
    isEnabled: true,
    isConnected: true,
    configMasked: { phoneId: '109848123910293', businessAccountId: '992019481729', webhookStatus: 'Verified' },
    lastTestedAt: '2026-03-03T08:00:00Z',
  },
  {
    id: 'int-02',
    key: 'sms',
    name: 'Global SMS Notification Service',
    provider: 'Twilio SMS Gateway',
    isEnabled: true,
    isConnected: true,
    configMasked: { accountSid: 'AC8819••••••••3910', fromNumber: '+1 (800) 555-APEX' },
    lastTestedAt: '2026-03-03T08:00:00Z',
  },
  {
    id: 'int-03',
    key: 'email',
    name: 'Transactional & Campaign Mailer',
    provider: 'SendGrid / AWS SES',
    isEnabled: true,
    isConnected: true,
    configMasked: { senderEmail: 'notifications@apexhealthclinics.com', spfDkim: 'Valid' },
    lastTestedAt: '2026-03-03T08:00:00Z',
  },
  {
    id: 'int-04',
    key: 'payment_gateway',
    name: 'Point-of-Sale & Online Card Processing',
    provider: 'Stripe Healthcare Connect',
    isEnabled: true,
    isConnected: true,
    configMasked: { publishableKey: 'pk_live_••••••••8120', webhookEndpoint: '/api/webhooks/stripe' },
    lastTestedAt: '2026-03-02T19:00:00Z',
  },
  {
    id: 'int-05',
    key: 'telemedicine',
    name: 'HIPAA-Compliant WebRTC Video Engine',
    provider: 'NovaCare WebRTC Core Mesh',
    isEnabled: true,
    isConnected: true,
    configMasked: { stunServer: 'stun.l.google.com:19302', encryption: 'AES-256-GCM End-to-End' },
    lastTestedAt: '2026-03-03T08:30:00Z',
  },
];

export const INITIAL_API_KEYS: ApiKeyRecord[] = [
  {
    id: 'key-01',
    name: 'Apex Lab Instruments Auto-Sync',
    keyMasked: 'nova_live_99f8••••••••••••••42a1',
    scope: ['labs.write', 'patients.read'],
    createdBy: 'Clinic Administrator',
    createdAt: '2026-01-15T10:00:00Z',
    lastUsedAt: '2026-03-03T08:14:00Z',
    status: 'Active',
  },
  {
    id: 'key-02',
    name: 'Third-Party Pharmacy Dispatch Hook',
    keyMasked: 'nova_live_33b1••••••••••••••98c4',
    scope: ['prescriptions.read'],
    createdBy: 'Clinic Administrator',
    createdAt: '2026-02-01T14:30:00Z',
    lastUsedAt: '2026-03-02T17:40:00Z',
    status: 'Active',
  },
];

export const INITIAL_WEBHOOKS: WebhookRecord[] = [
  {
    id: 'wh-01',
    name: 'Hospital ERP Syncer',
    endpointUrl: 'https://erp.apexhealthpartner.com/api/webhooks/clinic-events',
    events: ['appointment.booked', 'invoice.paid', 'patient.created'],
    status: 'Active',
    signingSecretMasked: 'whsec_9918••••••••••••21',
    lastDeliveryAt: '2026-03-03T08:15:00Z',
    successCount: 1420,
    failureCount: 2,
  },
];

export const INITIAL_FEATURE_FLAGS: FeatureFlag[] = [
  { id: 'ff-01', key: 'telemedicine_enabled', name: 'Virtual Telemedicine Video Rooms', description: 'Enable one-click encrypted video consultations with patient portal links.', isGlobalEnabled: true },
  { id: 'ff-02', key: 'two_way_crm_automation', name: 'Two-Way WhatsApp / SMS Automation Engine', description: 'Interactive bot responses parsing CONFIRM, CANCEL, and RESCHEDULE keyword replies.', isGlobalEnabled: true },
  { id: 'ff-03', key: 'prescription_safety_check', name: 'Prescription Drug Safety & Allergy Validator', description: 'Real-time contraindication and cross-allergy checks during prescription creation.', isGlobalEnabled: true },
  { id: 'ff-04', key: 'insurance_claims_portal', name: 'TPA & Insurance Claims Pre-Auth Subsystem', description: 'End-to-end claim settlement records, member validations, and copay breakdowns.', isGlobalEnabled: true },
  { id: 'ff-05', key: 'ai_copilot_summarizer', name: 'Gemini AI Clinical Consultation Copilot', description: 'Synthesizes chief complaints and patient history into structured medical notes.', isGlobalEnabled: true },
];

export const INITIAL_SAAS_PLANS: SaaSPlan[] = [
  {
    id: 'plan-starter',
    name: 'Starter',
    priceMonthly: 199,
    maxBranches: 1,
    maxUsers: 5,
    maxDoctors: 3,
    maxPatients: 2000,
    maxAppointmentsMonthly: 500,
    maxStorageGB: 25,
    features: ['Single Branch', 'Digital Prescriptions', 'Basic Invoicing', 'Email Reminders'],
  },
  {
    id: 'plan-pro',
    name: 'Professional',
    priceMonthly: 499,
    maxBranches: 3,
    maxUsers: 25,
    maxDoctors: 12,
    maxPatients: 10000,
    maxAppointmentsMonthly: 2500,
    maxStorageGB: 100,
    features: ['Multi-Branch Support', 'WhatsApp Business API', 'Inventory & Pharmacy', 'Lab Diagnostic Orders', 'Full CRM Suite'],
  },
  {
    id: 'plan-enterprise',
    name: 'Enterprise',
    priceMonthly: 999,
    maxBranches: 10,
    maxUsers: 100,
    maxDoctors: 50,
    maxPatients: 50000,
    maxAppointmentsMonthly: 15000,
    maxStorageGB: 500,
    features: ['Unlimited Branches', 'Telemedicine Suite', 'Insurance & TPA EDI', 'Audit & HIPAA Compliance', 'Custom API & Webhooks', 'Dedicated Account Mgr'],
  },
];

export const INITIAL_SUBSCRIPTIONS: OrganizationSubscription[] = [
  {
    id: 'sub-01',
    organizationId: 'org-01',
    planId: 'plan-enterprise',
    planName: 'Enterprise',
    status: 'Active',
    startDate: '2026-01-01T00:00:00Z',
    currentPeriodStart: '2026-03-01T00:00:00Z',
    currentPeriodEnd: '2026-04-01T00:00:00Z',
    autoRenew: true,
  },
];

export const INITIAL_USAGE_METRICS: UsageMetricRecord[] = [
  { organizationId: 'org-01', metric: 'branches', currentUsage: 2, planLimit: 10 },
  { organizationId: 'org-01', metric: 'doctors', currentUsage: 6, planLimit: 50 },
  { organizationId: 'org-01', metric: 'users', currentUsage: 14, planLimit: 100 },
  { organizationId: 'org-01', metric: 'patients', currentUsage: 24, planLimit: 50000 },
  { organizationId: 'org-01', metric: 'appointments_this_month', currentUsage: 68, planLimit: 15000 },
  { organizationId: 'org-01', metric: 'storage_gb', currentUsage: 4.8, planLimit: 500 },
  { organizationId: 'org-01', metric: 'campaigns', currentUsage: 3, planLimit: 50 },
];

export const INITIAL_ANNOUNCEMENTS: SystemAnnouncement[] = [
  {
    id: 'ann-01',
    title: 'HIPAA Security Protocol & Annual Audit Update',
    message: 'All clinical staff must verify multi-factor authentication (2FA) by the end of this week. Patient export logs will undergo automated spot-checks.',
    priority: 'High',
    targetOrganizationIds: ['org-01'],
    startAt: '2026-03-01T00:00:00Z',
    endAt: '2026-03-31T23:59:59Z',
    status: 'Active',
  },
  {
    id: 'ann-02',
    title: 'Spring CME Leave Registration Now Open',
    message: 'Physicians wishing to take CME leave for Q2 conferences must submit leave requests through the HR portal at least 14 days in advance.',
    priority: 'Low',
    targetOrganizationIds: ['org-01'],
    startAt: '2026-03-01T00:00:00Z',
    endAt: '2026-04-15T23:59:59Z',
    status: 'Active',
  },
];

// ============================================================
// PHASE 8: TELEMEDICINE, INSURANCE & CLINICAL SAFETY SEEDS
// ============================================================

export const INITIAL_TELEMEDICINE_ROOMS: TelemedicineRoom[] = [
  {
    id: 'tel-01',
    appointmentId: 'apt-04',
    appointmentNumber: 'APT-2026-004',
    patientId: 'pat-04',
    patientName: 'David Lee',
    doctorId: 'doc-01',
    doctorName: 'Dr. Sarah Jenkins, MD',
    doctorSpecialty: 'General Medicine',
    scheduledStartTime: '2026-03-03T11:00:00Z',
    status: 'Waiting for Doctor',
    roomId: 'nova-room-48912',
    roomTokenDoctor: 'tok-doc-884210',
    roomTokenPatient: 'tok-pat-991823',
    consultationNotes: 'Patient experiencing mild fever and fatigue for 3 days. Virtual triage requested.',
  },
  {
    id: 'tel-02',
    appointmentId: 'apt-08',
    appointmentNumber: 'APT-2026-008',
    patientId: 'pat-02',
    patientName: 'Jane Smith',
    doctorId: 'doc-02',
    doctorName: 'Dr. Michael Chen, MD',
    doctorSpecialty: 'Cardiology',
    scheduledStartTime: '2026-03-03T14:30:00Z',
    status: 'Scheduled',
    roomId: 'nova-room-55102',
    roomTokenDoctor: 'tok-doc-331092',
    roomTokenPatient: 'tok-pat-119482',
    consultationNotes: 'Post-medication blood pressure titration follow-up.',
  },
];

export const INITIAL_TELEMEDICINE_MESSAGES: TelemedicineMessage[] = [
  {
    id: 'tm-01',
    roomId: 'nova-room-48912',
    senderRole: 'SYSTEM',
    senderName: 'Apex Virtual Assistant',
    content: 'Room initialized. End-to-end encrypted WebRTC channel active.',
    timestamp: '2026-03-03T10:58:00Z',
  },
  {
    id: 'tm-02',
    roomId: 'nova-room-48912',
    senderRole: 'PATIENT',
    senderName: 'David Lee',
    content: 'Good morning Dr. Jenkins. I have uploaded my home temperature log.',
    timestamp: '2026-03-03T10:59:15Z',
  },
];

export const INITIAL_INSURANCE_PROVIDERS: InsuranceProvider[] = [
  {
    id: 'ins-01',
    name: 'Blue Cross Blue Shield Healthcare',
    code: 'BCBS-US',
    tpaName: 'CareFirst TPA Administrators',
    contactPerson: 'Amanda Vance (Provider Relations)',
    phone: '+1 (800) 444-BCBS',
    email: 'claims@bcbs-healthnetwork.com',
    portalUrl: 'https://provider.bcbs-portal.com',
    claimSubmissionMethod: 'Online Portal',
    status: 'Active',
  },
  {
    id: 'ins-02',
    name: 'UnitedHealthcare Global Plan',
    code: 'UHC-01',
    tpaName: 'Optum Health TPA',
    contactPerson: 'Robert Miller (Claims Officer)',
    phone: '+1 (877) 842-8212',
    email: 'edi-claims@uhc-portal.com',
    portalUrl: 'https://optumhealthclaims.com',
    claimSubmissionMethod: 'API',
    status: 'Active',
  },
  {
    id: 'ins-03',
    name: 'Aetna Health & Life',
    code: 'AETNA-MED',
    tpaName: 'Meritain Health TPA',
    contactPerson: 'Lisa Henderson',
    phone: '+1 (800) 872-3862',
    email: 'claims@aetnahealth.com',
    claimSubmissionMethod: 'Online Portal',
    status: 'Active',
  },
  {
    id: 'ins-04',
    name: 'Cigna Global Health Benefits',
    code: 'CIGNA-CORP',
    tpaName: 'Express Scripts TPA',
    contactPerson: 'Kevin Patel',
    phone: '+1 (800) 997-1654',
    email: 'provider.services@cigna.com',
    claimSubmissionMethod: 'Email EDI',
    status: 'Active',
  },
];

export const INITIAL_INSURANCE_POLICIES: InsurancePolicy[] = [
  {
    id: 'pol-01',
    patientId: 'pat-01',
    patientName: 'John Doe',
    providerId: 'ins-01',
    providerName: 'Blue Cross Blue Shield Healthcare',
    tpaName: 'CareFirst TPA Administrators',
    policyNumber: 'BCBS-NY-994821',
    memberId: 'MEM-8829104',
    planName: 'Preferred Comprehensive Gold PPO',
    coverageLimit: 25000,
    remainingBalance: 21850,
    validFrom: '2026-01-01',
    validUntil: '2026-12-31',
    status: 'Active',
  },
  {
    id: 'pol-02',
    patientId: 'pat-02',
    patientName: 'Jane Smith',
    providerId: 'ins-02',
    providerName: 'UnitedHealthcare Global Plan',
    tpaName: 'Optum Health TPA',
    policyNumber: 'UHC-CORP-448102',
    memberId: 'OPT-7712049',
    planName: 'Optum Choice Plus Silver',
    coverageLimit: 15000,
    remainingBalance: 14200,
    validFrom: '2026-01-01',
    validUntil: '2026-12-31',
    status: 'Active',
  },
  {
    id: 'pol-03',
    patientId: 'pat-03',
    patientName: 'Robert Johnson',
    providerId: 'ins-03',
    providerName: 'Aetna Health & Life',
    tpaName: 'Meritain Health TPA',
    policyNumber: 'AET-IND-552918',
    memberId: 'AET-9938102',
    planName: 'Aetna Open Access Advantage',
    coverageLimit: 30000,
    remainingBalance: 28600,
    validFrom: '2026-01-01',
    validUntil: '2026-12-31',
    status: 'Active',
  },
];

export const INITIAL_PRE_AUTHORIZATIONS: PreAuthorization[] = [
  {
    id: 'pre-01',
    preauthNumber: 'PA-2026-001',
    patientId: 'pat-01',
    patientName: 'John Doe',
    providerId: 'ins-01',
    providerName: 'Blue Cross Blue Shield Healthcare',
    policyNumber: 'BCBS-NY-994821',
    requestedProcedure: 'Right Knee Diagnostic MRI & Arthroscopic Joint Evaluation',
    estimatedCost: 1850,
    doctorId: 'doc-04',
    doctorName: 'Dr. David Kim, MD',
    clinicalJustification: 'Patient presents with persistent severe joint effusion, joint locking, and MRI evidence of Grade 3 medial meniscus tear.',
    documents: ['Radiology_Request.pdf', 'Clinical_History_Summary.pdf'],
    status: 'Approved',
    approvedAmount: 1650,
    approvalNumber: 'AUTH-BCBS-9921',
    validUntil: '2026-04-15',
    reviewerRemarks: 'Approved with 10% standard out-of-pocket copay responsibility.',
    submittedAt: '2026-02-20T10:00:00Z',
    decidedAt: '2026-02-23T14:30:00Z',
    createdAt: '2026-02-20T10:00:00Z',
  },
  {
    id: 'pre-02',
    preauthNumber: 'PA-2026-002',
    patientId: 'pat-03',
    patientName: 'Robert Johnson',
    providerId: 'ins-03',
    providerName: 'Aetna Health & Life',
    policyNumber: 'AET-IND-552918',
    requestedProcedure: 'Stress Echocardiography & 48-Hour Holter Monitor',
    estimatedCost: 920,
    doctorId: 'doc-02',
    doctorName: 'Dr. Michael Chen, MD',
    clinicalJustification: 'Recurrent exertional palpitations, non-sustained ventricular ectopic beats on resting ECG.',
    documents: ['Resting_ECG_Strip.pdf'],
    status: 'Under Review',
    submittedAt: '2026-03-01T11:00:00Z',
    createdAt: '2026-03-01T11:00:00Z',
  },
];

export const INITIAL_INSURANCE_CLAIMS: InsuranceClaim[] = [
  {
    id: 'clm-01',
    claimNumber: 'CLM-2026-001',
    patientId: 'pat-01',
    patientName: 'John Doe',
    providerId: 'ins-01',
    providerName: 'Blue Cross Blue Shield Healthcare',
    policyNumber: 'BCBS-NY-994821',
    memberId: 'MEM-8829104',
    invoiceId: 'inv-01',
    invoiceNumber: 'INV-2026-001',
    servicesSummary: 'Specialist Consultation, Comprehensive Blood Panel, ECG',
    totalClaimAmount: 380,
    approvedAmount: 340,
    patientCopayAmount: 40,
    rejectedAmount: 0,
    settlementStatus: 'Settled',
    status: 'Settled',
    submissionDate: '2026-02-16',
    settlementDate: '2026-02-25',
    paymentReference: 'EFT-BCBS-991820',
    documents: [{ title: 'Signed CMS-1500 Claim Form', fileUrl: '#', category: 'Claim Form' }],
    createdAt: '2026-02-16T14:00:00Z',
  },
  {
    id: 'clm-02',
    claimNumber: 'CLM-2026-002',
    patientId: 'pat-02',
    patientName: 'Jane Smith',
    providerId: 'ins-02',
    providerName: 'UnitedHealthcare Global Plan',
    policyNumber: 'UHC-CORP-448102',
    memberId: 'OPT-7712049',
    invoiceId: 'inv-02',
    invoiceNumber: 'INV-2026-002',
    servicesSummary: 'Cardiology Consultation, Lipid Profile, Echocardiogram',
    totalClaimAmount: 520,
    approvedAmount: 480,
    patientCopayAmount: 40,
    rejectedAmount: 0,
    settlementStatus: 'Unsettled',
    status: 'Under Review',
    submissionDate: '2026-02-28',
    documents: [{ title: 'Cardiology Clinical Assessment Note', fileUrl: '#', category: 'Clinical Note' }],
    createdAt: '2026-02-28T16:20:00Z',
  },
];

export const INITIAL_CLAIM_SETTLEMENTS: ClaimSettlement[] = [
  {
    id: 'set-01',
    claimId: 'clm-01',
    claimNumber: 'CLM-2026-001',
    invoiceId: 'inv-01',
    totalInvoice: 380,
    approvedByInsurance: 340,
    patientCopay: 40,
    rejectedPortion: 0,
    insuranceSettlementRef: 'EFT-BCBS-991820',
    settledAt: '2026-02-25T15:00:00Z',
    recordedBy: 'Daniel Weber, CPA',
  },
];

export const INITIAL_DOCTOR_SHIFTS: DoctorShift[] = [
  {
    id: 'dshift-01',
    shiftType: 'Morning',
    date: '2026-03-03',
    startTime: '08:00',
    endTime: '15:00',
    doctorId: 'doc-01',
    doctorName: 'Dr. Sarah Jenkins, MD',
    branchId: 'branch-01',
    branchName: 'Downtown Central Clinic',
    departmentName: 'General Medicine',
    isOnCall: false,
    status: 'Active',
  },
  {
    id: 'dshift-02',
    shiftType: 'Morning',
    date: '2026-03-03',
    startTime: '09:00',
    endTime: '16:00',
    doctorId: 'doc-02',
    doctorName: 'Dr. Michael Chen, MD',
    branchId: 'branch-01',
    branchName: 'Downtown Central Clinic',
    departmentName: 'Cardiology',
    isOnCall: false,
    status: 'Active',
  },
  {
    id: 'dshift-03',
    shiftType: 'On Call',
    date: '2026-03-03',
    startTime: '16:00',
    endTime: '08:00',
    doctorId: 'doc-04',
    doctorName: 'Dr. David Kim, MD',
    branchId: 'branch-01',
    branchName: 'Downtown Central Clinic',
    departmentName: 'Orthopedics',
    isOnCall: true,
    status: 'Scheduled',
  },
  {
    id: 'dshift-04',
    shiftType: 'Morning',
    date: '2026-03-04',
    startTime: '08:00',
    endTime: '15:00',
    doctorId: 'doc-01',
    doctorName: 'Dr. Sarah Jenkins, MD',
    branchId: 'branch-01',
    branchName: 'Downtown Central Clinic',
    departmentName: 'General Medicine',
    isOnCall: false,
    status: 'Scheduled',
  },
  {
    id: 'dshift-05',
    shiftType: 'Evening',
    date: '2026-03-04',
    startTime: '14:00',
    endTime: '21:00',
    doctorId: 'doc-05',
    doctorName: 'Dr. Priya Patel, MD',
    branchId: 'branch-01',
    branchName: 'Downtown Central Clinic',
    departmentName: 'Pediatrics',
    isOnCall: false,
    status: 'Scheduled',
  },
];

export const INITIAL_ON_CALL_ROSTERS: OnCallRoster[] = [
  {
    id: 'oncall-01',
    date: '2026-03-03',
    department: 'Cardiology & Emergency Triage',
    branchId: 'branch-01',
    branchName: 'Downtown Central Clinic',
    primaryDoctorId: 'doc-02',
    primaryDoctorName: 'Dr. Michael Chen, MD',
    primaryDoctorPhone: '+1 (555) 345-6789',
    backupDoctorId: 'doc-01',
    backupDoctorName: 'Dr. Sarah Jenkins, MD',
    backupDoctorPhone: '+1 (555) 234-5678',
    status: 'Published',
  },
  {
    id: 'oncall-02',
    date: '2026-03-03',
    department: 'Orthopedics & Acute Trauma',
    branchId: 'branch-01',
    branchName: 'Downtown Central Clinic',
    primaryDoctorId: 'doc-04',
    primaryDoctorName: 'Dr. David Kim, MD',
    primaryDoctorPhone: '+1 (555) 789-0123',
    backupDoctorId: 'doc-01',
    backupDoctorName: 'Dr. Sarah Jenkins, MD',
    backupDoctorPhone: '+1 (555) 234-5678',
    status: 'Published',
  },
  {
    id: 'oncall-03',
    date: '2026-03-04',
    department: 'General Medicine & Family Practice',
    branchId: 'branch-01',
    branchName: 'Downtown Central Clinic',
    primaryDoctorId: 'doc-01',
    primaryDoctorName: 'Dr. Sarah Jenkins, MD',
    primaryDoctorPhone: '+1 (555) 234-5678',
    backupDoctorId: 'doc-05',
    backupDoctorName: 'Dr. Priya Patel, MD',
    backupDoctorPhone: '+1 (555) 555-0199',
    status: 'Published',
  },
];

export const INITIAL_DRUG_SAFETY_WARNINGS: DrugSafetyWarning[] = [
  {
    id: 'dsw-01',
    medicineName: 'Amoxicillin 500mg',
    warningType: 'ALLERGY',
    severity: 'Critical',
    reason: 'Patient has documented Penicillin hypersensitivity. High risk of immediate anaphylaxis.',
    relatedMedicationOrAllergen: 'Penicillin',
    recommendation: 'Switch to Macrolide (e.g. Azithromycin) or Fluoroquinolone.',
    isDismissed: false,
    isOverridden: false,
  },
  {
    id: 'dsw-02',
    medicineName: 'Aspirin 81mg',
    warningType: 'INTERACTION',
    severity: 'High',
    reason: 'Concurrent use with Warfarin significantly compounds gastrointestinal hemorrhage risk.',
    relatedMedicationOrAllergen: 'Warfarin 5mg',
    recommendation: 'Evaluate benefit versus bleeding risk; consider gastroprotective PPI co-therapy.',
    isDismissed: true,
    isOverridden: true,
    overrideReason: 'Cardiologist approved post-stent dual therapy under tight weekly INR surveillance.',
    overriddenByDoctorId: 'doc-02',
    overriddenAt: '2026-02-28T15:20:00Z',
  },
];

export const INITIAL_DRUG_SAFETY_EVENTS: DrugSafetyEvent[] = [
  {
    id: 'dse-01',
    patientId: 'pat-01',
    doctorId: 'doc-02',
    doctorName: 'Dr. Michael Chen, MD',
    medicineName: 'Aspirin 81mg',
    warningType: 'INTERACTION',
    severity: 'High',
    reason: 'Concurrent use with Warfarin compounds bleeding risk.',
    actionTaken: 'OVERRIDDEN',
    overrideReason: 'Cardiologist approved post-stent dual therapy with INR monitoring.',
    timestamp: '2026-02-28T15:20:00Z',
  },
];

export const INITIAL_BACKGROUND_JOBS: BackgroundJobRecord[] = [
  {
    id: 'job-01',
    queue: 'Appointment Reminders',
    jobName: 'Send 24h WhatsApp Reminder to 18 Scheduled Patients',
    status: 'Completed',
    attemptCount: 1,
    maxAttempts: 3,
    payloadSummary: 'Sent 18 templates with confirmation deep-links.',
    startedAt: '2026-03-03T08:00:00Z',
    completedAt: '2026-03-03T08:00:18Z',
  },
  {
    id: 'job-02',
    queue: 'Insurance Sync',
    jobName: 'Electronic Remittance Advice (ERA) Batch Ingestion',
    status: 'Completed',
    attemptCount: 1,
    maxAttempts: 3,
    payloadSummary: 'Processed 4 remittance vouchers from Optum & BCBS.',
    startedAt: '2026-03-03T07:30:00Z',
    completedAt: '2026-03-03T07:30:45Z',
  },
  {
    id: 'job-03',
    queue: 'Data Exports',
    jobName: 'Monthly Financial Ledger Archive for Q1',
    status: 'Completed',
    attemptCount: 1,
    maxAttempts: 3,
    payloadSummary: 'Generated zip package with 12 spreadsheets.',
    startedAt: '2026-03-01T03:00:00Z',
    completedAt: '2026-03-01T03:02:10Z',
  },
];

export const INITIAL_HEALTH_CHECKS: SystemHealthCheck[] = [
  { service: 'API Server', status: 'Healthy', latencyMs: 14, lastCheckedAt: '2026-03-03T08:30:00Z', message: 'All cluster pods responsive' },
  { service: 'Database', status: 'Healthy', latencyMs: 8, lastCheckedAt: '2026-03-03T08:30:00Z', message: 'Replication lag: 0ms' },
  { service: 'Redis Queue', status: 'Healthy', latencyMs: 2, lastCheckedAt: '2026-03-03T08:30:00Z', message: '0 pending failed jobs' },
  { service: 'Object Storage', status: 'Healthy', latencyMs: 28, lastCheckedAt: '2026-03-03T08:30:00Z', message: 'GCS bucket accessible' },
  { service: 'WhatsApp Gateway', status: 'Healthy', latencyMs: 95, lastCheckedAt: '2026-03-03T08:30:00Z', message: 'Meta Cloud API 200 OK' },
  { service: 'Telemedicine WebRTC', status: 'Healthy', latencyMs: 42, lastCheckedAt: '2026-03-03T08:30:00Z', message: 'TURN/STUN relays nominal' },
  { service: 'Payment Gateway', status: 'Healthy', latencyMs: 110, lastCheckedAt: '2026-03-03T08:30:00Z', message: 'Stripe webhooks operational' },
];
